### ISSUE TITLE
line 29 problem 

### ISSUE THREAD

**Issue by sachalethug** [moom825/Discord-QR-Token-Grabber#3]
When I want to create qr code I have this : 

  File "C:\Users\USER\Desktop\Discord-QR-Token-Grabber-main\Discord-QR.py", line 29, in <module>
    qrcode = classe.find('img')['src']
AttributeError: 'NoneType' object has no attribute 'find'

Is my python version ? (I use 3.9.7)

**Comment by moom825** [comment]
fixed
